quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173,https://main.d1ufvt86vjqu8r.amplifyapp.com 

# configuration for the database connection
quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL}
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD}
quarkus.hibernate-orm.schema-management.strategy=update